### ISSUE TITLE
Bug with LLVM mode on DDM when trying to set default reset_stateful_function_when

### ISSUE THREAD

**Issue by davidt0x** [PrincetonUniversity/PsyNeuLink#1935]
This bug is related to a simple modification I am trying to implement in DDM. The branch with just the modification that is reproducing the error is here:

[bug/ddm_llvm_bug](https://github.com/PrincetonUniversity/PsyNeuLink/tree/bug/ddm_llvm_bug)

I am trying to make the default behavior of the DDM to reset stateful functions at each trial start. I thought I could do this by setting the attribute reset_stateful_function_when to AtTrialStart in __init__. This seems to cause a problem with compiled mode execution.

Here is a minimal script to reproduce the error:

```
from psyneulink import *
comp = Composition(pathways=DDM(function=DriftDiffusionIntegrator()))
results = comp.run([1.0], execution_mode=ExecutionMode.LLVM)
```

This is the result:

```
C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\components\functions\transferfunctions.py:2979: UserWarning: Shape mismatch: (LinearMatrix LinearMatrix Function-1) (in (MappingProjection (DECISION_VARIABLE) to (OUTPUT_CIM_DDM-0_DECISION_VARIABLE))) got 2D input: [[0.]]
  warnings.warn("Shape mismatch: {} (in {}) got 2D input: {}".format(self, self.owner, self.defaults.variable))
C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\components\functions\transferfunctions.py:2982: UserWarning: Shape mismatch: (LinearMatrix LinearMatrix Function-1) (in (MappingProjection (DECISION_VARIABLE) to (OUTPUT_CIM_DDM-0_DECISION_VARIABLE))) has 2D output: [[0.]]
  warnings.warn("Shape mismatch: {} (in {}) has 2D output: {}".format(self, self.owner, self.defaults.value))
C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\llvm\codegen.py:744: UserWarning: Shape mismatch: Projection ((MappingProjection (DECISION_VARIABLE) to (OUTPUT_CIM_DDM-0_DECISION_VARIABLE))) results does not match the receiver state((InputPort OUTPUT_CIM_DDM-0_DECISION_VARIABLE)) input: [[0.]] vs. [[0.]]
  warnings.warn("Shape mismatch: Projection ({}) results does not match the receiver state({}) input: {} vs. {}".format(proj, proj.receiver, proj.defaults.value, proj.receiver.defaults.variable))
C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\components\functions\transferfunctions.py:2979: UserWarning: Shape mismatch: (LinearMatrix LinearMatrix Function-2) (in (MappingProjection (RESPONSE_TIME) to (OUTPUT_CIM_DDM-0_RESPONSE_TIME))) got 2D input: [[0.]]
  warnings.warn("Shape mismatch: {} (in {}) got 2D input: {}".format(self, self.owner, self.defaults.variable))
C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\components\functions\transferfunctions.py:2982: UserWarning: Shape mismatch: (LinearMatrix LinearMatrix Function-2) (in (MappingProjection (RESPONSE_TIME) to (OUTPUT_CIM_DDM-0_RESPONSE_TIME))) has 2D output: [[0.]]
  warnings.warn("Shape mismatch: {} (in {}) has 2D output: {}".format(self, self.owner, self.defaults.value))
C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\llvm\codegen.py:744: UserWarning: Shape mismatch: Projection ((MappingProjection (RESPONSE_TIME) to (OUTPUT_CIM_DDM-0_RESPONSE_TIME))) results does not match the receiver state((InputPort OUTPUT_CIM_DDM-0_RESPONSE_TIME)) input: [[0.]] vs. [[0.]]
  warnings.warn("Shape mismatch: Projection ({}) results does not match the receiver state({}) input: {} vs. {}".format(proj, proj.receiver, proj.defaults.value, proj.receiver.defaults.variable))
Traceback (most recent call last):
  File "C:\Users\david\anaconda3\envs\psyneulink\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c6b227161739>", line 1, in <module>
    runfile('C:/Users/david/AppData/Roaming/JetBrains/PyCharm2020.3/scratches/scratch.py', wdir='C:/Users/david/AppData/Roaming/JetBrains/PyCharm2020.3/scratches')
  File "C:\Program Files\JetBrains\PyCharm 2020.1.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/david/AppData/Roaming/JetBrains/PyCharm2020.3/scratches/scratch.py", line 7, in <module>
    results = comp.run([1.0], execution_mode=ExecutionMode.LLVM)
  File "C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\globals\context.py", line 734, in wrapper
    return func(*args, context=context, **kwargs)
  File "C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\compositions\composition.py", line 8504, in run
    trial_output = self.execute(inputs=execution_stimuli,
  File "C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\globals\context.py", line 734, in wrapper
    return func(*args, context=context, **kwargs)
  File "C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\compositions\composition.py", line 9027, in execute
    _comp_ex.execute_node(self.input_CIM, inputs)
  File "C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\llvm\execution.py", line 492, in execute_node
    self._bin_func(self._state_struct, self._param_struct,
  File "C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\llvm\execution.py", line 356, in _state_struct
    return self._get_compilation_param('_state', '_get_state_initializer', 0)
  File "C:\Users\david\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\llvm\execution.py", line 81, in _get_compilation_param
    struct = struct_ty(*initializer)
RuntimeError: (struct_1) <class 'RuntimeError'>: (struct_2) <class 'RuntimeError'>: (c_double_Array_1_Array_1_Array_2_Array_1) <class 'RuntimeError'>: (c_double_Array_1_Array_1_Array_2) <class 'RuntimeError'>: (c_double_Array_1_Array_1) <class 'TypeError'>: expected c_double_Array_1 instance, got int
```

**Comment by jvesely** [comment]
looks like like the `state` initializer does not match the expected format.
Dumping the state structure gives:
```
 _state <class 'psyneulink.core.llvm.builder_context.struct_0'>
	 DDM-0 <class 'psyneulink.core.llvm.builder_context.struct_2'>
		 _parameter_ports <class 'psyneulink.core.llvm.builder_context.struct_3'> (((True,), ((True,), (0,), ((0, 0, 0, 0, 0),), (0,)), (0,), ((0, 0, 0, 0, 0),), (0,)), ((True,), ((True,), (0,), ((0, 0, 0, 0, 0),), (0,)), (0,), ((0, 0, 0, 0, 0),), (0,)), ((True,), ((True,), (0,), ((0, 0, 0, 0, 0),), (0,)), (0,), ((0, 0, 0, 0, 0),), (0,)), ((True,), ((True,), (0,), ((0, 0, 0, 0, 0),), (0,)), (0,), ((0, 0, 0, 0, 0),), (0,)), ((True,), ((True,), (0,), ((0, 0, 0, 0, 0),), (0,)), (0,), ((0, 0, 0, 0, 0),), (0,)))
		 is_finished_flag <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (True,)
		 function <class 'psyneulink.core.llvm.builder_context.struct_6'>
			 execution_count <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (2,)
			 num_executions <class 'psyneulink.core.llvm.builder_context.c_int_Array_5_Array_1'> ((0, 0, 0, 0, 0),)
			 previous_time <class 'psyneulink.core.llvm.builder_context.c_double_Array_1_Array_1'> ((0.0,),)
			 previous_value <class 'psyneulink.core.llvm.builder_context.c_double_Array_1_Array_1_Array_1'> (((0,),),)
			 num_executions_before_finished <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
			 is_finished_flag <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (True,)
			 random_state <class 'psyneulink.core.llvm.builder_context.struct_7_Array_1'> (((...), 8, 0, 0.0),)
		 input_ports <class 'psyneulink.core.llvm.builder_context.struct_8'> (((True,), ((True,), (2,), ((0, 0, 0, 0, 0),), (0,)), (0,), ((0, 0, 0, 0, 0),), (0,)),)
		 random_state <class 'psyneulink.core.llvm.builder_context.struct_7_Array_1'> (((...), 624, 0, 0.0),)
		 execution_count <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
		 num_executions <class 'psyneulink.core.llvm.builder_context.c_int_Array_5_Array_1'> ((0, 0, 0, 0, 0),)
		 output_ports <class 'psyneulink.core.llvm.builder_context.struct_9'> (((True,), ((True,), (0,), ((0, 0, 0, 0, 0),), (0,)), (0,), ((0, 0, 0, 0, 0),), (0,)), ((True,), ((True,), (0,), ((0, 0, 0, 0, 0),), (0,)), (0,), ((0, 0, 0, 0, 0),), (0,)))
		 value <class 'psyneulink.core.llvm.builder_context.c_double_Array_1_Array_1_Array_2_Array_1'> (((0,), (0.0,)),)
		 num_executions_before_finished <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
	 (INPUT_CIM_DDM-0_InputPort-0) to (DDM-0-InputPort-0) <class 'psyneulink.core.llvm.builder_context.struct_4'>
		 is_finished_flag <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (True,)
		 function <class 'psyneulink.core.llvm.builder_context.struct_5'>
			 is_finished_flag <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (True,)
			 execution_count <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
			 num_executions <class 'psyneulink.core.llvm.builder_context.c_int_Array_5_Array_1'> ((0, 0, 0, 0, 0),)
			 num_executions_before_finished <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
		 execution_count <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
		 num_executions <class 'psyneulink.core.llvm.builder_context.c_int_Array_5_Array_1'> ((0, 0, 0, 0, 0),)
		 num_executions_before_finished <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
	 (DECISION_VARIABLE) to (OUTPUT_CIM_DDM-0_DECISION_VARIABLE) <class 'psyneulink.core.llvm.builder_context.struct_4'>
		 is_finished_flag <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (True,)
		 function <class 'psyneulink.core.llvm.builder_context.struct_5'>
			 is_finished_flag <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (True,)
			 execution_count <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
			 num_executions <class 'psyneulink.core.llvm.builder_context.c_int_Array_5_Array_1'> ((0, 0, 0, 0, 0),)
			 num_executions_before_finished <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
		 execution_count <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
		 num_executions <class 'psyneulink.core.llvm.builder_context.c_int_Array_5_Array_1'> ((0, 0, 0, 0, 0),)
		 num_executions_before_finished <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
	 (RESPONSE_TIME) to (OUTPUT_CIM_DDM-0_RESPONSE_TIME) <class 'psyneulink.core.llvm.builder_context.struct_4'>
		 is_finished_flag <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (True,)
		 function <class 'psyneulink.core.llvm.builder_context.struct_5'>
			 is_finished_flag <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (True,)
			 execution_count <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
			 num_executions <class 'psyneulink.core.llvm.builder_context.c_int_Array_5_Array_1'> ((0, 0, 0, 0, 0),)
			 num_executions_before_finished <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
		 execution_count <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
		 num_executions <class 'psyneulink.core.llvm.builder_context.c_int_Array_5_Array_1'> ((0, 0, 0, 0, 0),)
		 num_executions_before_finished <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
	 is_finished_flag <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (True,)
	 execution_count <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
	 num_executions <class 'psyneulink.core.llvm.builder_context.c_int_Array_5_Array_1'> ((0, 0, 0, 0, 0),)
	 num_executions_before_finished <class 'psyneulink.core.llvm.builder_context.c_double_Array_1'> (0,)
	 ```

the only `c_double_Array_1_Array_1_Array_2_Array_1` field that I see in `struct_2` is `value`. There the initialzier is `(((0,), (0.0,)),)`. The first `0` is integer, while the second one is float.

**Comment by jvesely** [comment]
Use execution mode `LLVMExec` or `LLVMRun`.
`LLVM` mode combined with `reset_when` mixes python and LLVM execution in an unsupported way
