### ISSUE TITLE
Psyneulink fails to install on python3.6 Linux

### ISSUE THREAD

**Issue by jvesely** [PrincetonUniversity/PsyNeuLink#2039]
```
pip3 install --user psyneulink
Collecting psyneulink
  Downloading https://files.pythonhosted.org/packages/30/dd/12a347c862791e52778040c1aec9357a4204282bc450805843000578e04f/psyneulink-0.8.8.1-py3-none-any.whl (1.3MB)
    100% |################################| 1.3MB 1.2MB/s 
Collecting graphviz<0.17.0 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/86/86/89ba50ba65928001d3161f23bfa03945ed18ea13a1d1d44a772ff1fa4e7a/graphviz-0.16-py2.py3-none-any.whl
Collecting llvmlite<0.37 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/19/66/6b2c49c7c68da48d17059882fdb9ad9ac9e5ac3f22b00874d7996e3c44a8/llvmlite-0.36.0.tar.gz (126kB)
    100% |################################| 133kB 5.6MB/s 
Collecting numpy<1.20.3 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
    100% |################################| 13.4MB 131kB/s 
Collecting networkx<2.6 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/f3/b7/c7f488101c0bb5e4178f3cde416004280fd40262433496830de8a8c21613/networkx-2.5.1-py3-none-any.whl (1.6MB)
    100% |################################| 1.6MB 1.0MB/s 
Collecting leabra-psyneulink<=0.3.2 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/3f/62/6cedb15e61fc4a77fb23a37126666258ab9ca33653e4d8360f65cf0fb641/leabra_psyneulink-0.3.2-py3-none-any.whl
Collecting grpcio<1.35.0 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/81/5e/168a7fa23a025beed6b7daa0981ace55e394a136db3082faed7d6cba4556/grpcio-1.34.1.tar.gz (21.1MB)
    100% |################################| 21.1MB 85kB/s 
Collecting toposort<1.7 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/f2/7d/55784e894ee0cde2474fb977ffd1651e74e840a9f92e1d847f7e3115d5ec/toposort-1.6-py2.py3-none-any.whl
Collecting pillow<8.1.0 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/5f/19/d4c25111d36163698396f93c363114cf1cddbacb24744f6612f25b6aa3d0/Pillow-8.0.1-cp36-cp36m-manylinux1_x86_64.whl (2.2MB)
    100% |################################| 2.2MB 755kB/s 
Collecting matplotlib<3.3.4 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/d2/43/2bd63467490036697e7be71444fafc7b236923d614d4521979a200c6b559/matplotlib-3.3.3-cp36-cp36m-manylinux1_x86_64.whl (11.6MB)
    100% |################################| 11.6MB 155kB/s 
Collecting torch<1.9.0,>=1.8.0; sys_platform != "win32" and platform_machine == "x86_64" and platform_python_implementation == "CPython" (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/dd/b9/824df420f6abf551e41bbaacbaa0be8321dc104f9f3803051513844dc310/torch-1.8.1-cp36-cp36m-manylinux1_x86_64.whl (804.1MB)
    100% |################################| 804.1MB 2.2kB/s 
Collecting elfi<0.8.1 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/bb/94/381256c017e29fb742a3e19565910f2947dca7c0341b3a2a1401b93f074c/elfi-0.8.0-py3-none-any.whl (162kB)
    100% |################################| 163kB 4.5MB/s 
Collecting autograd<=1.3 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/23/12/b58522dc2cbbd7ab939c7b8e5542c441c9a06a8eccb00b3ecac04a739896/autograd-1.3.tar.gz
Collecting rich<10.2,>=10.1 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/1a/da/2a1f064dc620ab47f3f826ae085384084b71ea05c8c21d67f1dfc29189ab/rich-10.1.0-py3-none-any.whl (201kB)
    100% |################################| 204kB 4.6MB/s 
Collecting typecheck-decorator<=1.2 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/e0/4d/c925353ad7a3b69ad9957748bdc709aa535df0a303f2d0318e02ad8f39d2/typecheck-decorator-1.2.zip
Collecting dill<=0.32 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/52/d6/79f40d230895fa1ce3b6af0d22e0ac79c65175dc069c194b79cc8e05a033/dill-0.3.3-py2.py3-none-any.whl (81kB)
    100% |################################| 81kB 6.0MB/s 
Collecting grpcio-tools<1.35.0 (from psyneulink)
  Downloading https://files.pythonhosted.org/packages/6b/9d/a5fa6506188e44393a225245c6898a5601caf6faa1e7093ed6af1b005fe3/grpcio-tools-1.34.1.tar.gz (2.1MB)
    100% |################################| 2.1MB 797kB/s 
Collecting decorator<5,>=4.3 (from networkx<2.6->psyneulink)
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting jupyter (from leabra-psyneulink<=0.3.2->psyneulink)
  Downloading https://files.pythonhosted.org/packages/83/df/0f5dd132200728a86190397e1ea87cd76244e42d39ec5e88efd25b2abd7e/jupyter-1.0.0-py2.py3-none-any.whl
Collecting bokeh>=0.12.6 (from leabra-psyneulink<=0.3.2->psyneulink)
  Downloading https://files.pythonhosted.org/packages/82/4c/5f5aa9907fb2f545974caade9fb83ade57f5b5efc37641764145413e94ef/bokeh-2.3.1.tar.gz (10.6MB)
    100% |################################| 10.6MB 167kB/s 
Collecting ipywidgets>=7.0 (from leabra-psyneulink<=0.3.2->psyneulink)
  Downloading https://files.pythonhosted.org/packages/11/53/084940a83a8158364e630a664a30b03068c25ab75243224d6b488800d43a/ipywidgets-7.6.3-py2.py3-none-any.whl (121kB)
    100% |################################| 122kB 5.5MB/s 
Collecting scipy (from leabra-psyneulink<=0.3.2->psyneulink)
  Downloading https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9MB)
    100% |################################| 25.9MB 68kB/s 
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from grpcio<1.35.0->psyneulink)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib<3.3.4->psyneulink)
  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
    100% |################################| 71kB 7.1MB/s 
Collecting kiwisolver>=1.0.1 (from matplotlib<3.3.4->psyneulink)
  Downloading https://files.pythonhosted.org/packages/a7/1b/cbd8ae738719b5f41592a12057ef5442e2ed5f5cb5451f8fc7e9f8875a1a/kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (1.1MB)
    100% |################################| 1.1MB 1.4MB/s 
Collecting python-dateutil>=2.1 (from matplotlib<3.3.4->psyneulink)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
    100% |################################| 235kB 4.2MB/s 
Collecting cycler>=0.10 (from matplotlib<3.3.4->psyneulink)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting dataclasses; python_version < "3.7" (from torch<1.9.0,>=1.8.0; sys_platform != "win32" and platform_machine == "x86_64" and platform_python_implementation == "CPython"->psyneulink)
  Downloading https://files.pythonhosted.org/packages/fe/ca/75fac5856ab5cfa51bbbcefa250182e50441074fdc3f803f6e76451fab43/dataclasses-0.8-py3-none-any.whl
Collecting typing-extensions (from torch<1.9.0,>=1.8.0; sys_platform != "win32" and platform_machine == "x86_64" and platform_python_implementation == "CPython"->psyneulink)
  Downloading https://files.pythonhosted.org/packages/2e/35/6c4fff5ab443b57116cb1aad46421fb719bed2825664e8fe77d66d99bcbc/typing_extensions-3.10.0.0-py3-none-any.whl
Collecting GPy>=1.0.9 (from elfi<0.8.1->psyneulink)
  Downloading https://files.pythonhosted.org/packages/67/95/976598f98adbfa918a480cb2d643f93fb555ca5b6c5614f76b69678114c1/GPy-1.9.9.tar.gz (995kB)
    100% |################################| 1.0MB 1.6MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-8mb8yt9d/numpy-1.20.2/setup.py", line 30, in <module>
        # DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
    RuntimeError: Python version >= 3.7 required.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-m8tacuwx/GPy/setup.py", line 192, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-8mb8yt9d/numpy-1.20.2/setup.py", line 30, in <module>
        # DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
    RuntimeError: Python version >= 3.7 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-m8tacuwx/GPy/
```

**Comment by jvesely** [comment]
The workaround is to install `numpy` first.

**Comment by jvesely** [comment]
Python 3.6 is no longer supported.
