### ISSUE TITLE
graphviz representation not working when creating the model programmatically

### ISSUE THREAD

**Issue by ddelpiano** [PrincetonUniversity/PsyNeuLink#3143]
As per title, when creating the model programmatically using the ports params for mechanisms and the composition api, the graphviz representation, graphviz fails to serialise the model representation in json format. Thanks!

stacktrace:

```
python test.py 
Traceback (most recent call last):
  File "/home/ddelpiano/miniconda3/envs/psyneu/lib/python3.10/site-packages/graphviz/backend/execute.py", line 91, in run_check
    proc.check_returncode()
  File "/home/ddelpiano/miniconda3/envs/psyneu/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '[PosixPath('dot'), '-Kdot', '-Tjson']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ddelpiano/test.py", line 19, in <module>
    gv_node.pipe('json', quiet=True).decode()
  File "/home/ddelpiano/miniconda3/envs/psyneu/lib/python3.10/site-packages/graphviz/piping.py", line 104, in pipe
    return self._pipe_legacy(format,
  File "/home/ddelpiano/miniconda3/envs/psyneu/lib/python3.10/site-packages/graphviz/_tools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "/home/ddelpiano/miniconda3/envs/psyneu/lib/python3.10/site-packages/graphviz/piping.py", line 121, in _pipe_legacy
    return self._pipe_future(format,
  File "/home/ddelpiano/miniconda3/envs/psyneu/lib/python3.10/site-packages/graphviz/piping.py", line 161, in _pipe_future
    return self._pipe_lines(*args, input_encoding=self.encoding, **kwargs)
  File "/home/ddelpiano/miniconda3/envs/psyneu/lib/python3.10/site-packages/graphviz/backend/piping.py", line 161, in pipe_lines
    proc = execute.run_check(cmd, capture_output=True, quiet=quiet, **kwargs)
  File "/home/ddelpiano/miniconda3/envs/psyneu/lib/python3.10/site-packages/graphviz/backend/execute.py", line 93, in run_check
    raise CalledProcessError(*e.args)
graphviz.backend.execute.CalledProcessError: Command '[PosixPath('dot'), '-Kdot', '-Tjson']' returned non-zero exit status 1. [stderr: b'Error: syntax error in line 1 \n... <i></i> ...\nin label of node output\nError: syntax error in line 1 \n... <i></i> ...\nin label of node mid\nError: syntax error in line 1 \n... <i></i> ...\nin label of node input\nWarning: node mid, port OutputPort-mid_OutputPort_0 unrecognized\nWarning: node output, port InputPort-output_InputPort_0 unrecognized\nWarning: node input, port OutputPort-input_OutputPort_0 unrecognized\nWarning: node mid, port InputPort-mid_InputPort_0 unrecognized\n']
```

model.py

```
import psyneulink as pnl
from psyneulink import *

output = pnl.ProcessingMechanism(function = pnl.Linear(slope=2,intercept=0,), name = 'output', output_ports = ['output_OutputPort_0'], input_ports = ['output_InputPort_0'])
mid = pnl.ProcessingMechanism(function = pnl.Linear(slope=2,intercept=0,), name = 'mid', output_ports = ['mid_OutputPort_0'], input_ports = ['mid_InputPort_0'])
input = pnl.ProcessingMechanism(function = pnl.Linear(slope=1,intercept=0,), name = 'input', output_ports = ['input_OutputPort_0'], input_ports = ['input_InputPort_0'])
link_mid_to_output = pnl.MappingProjection(sender = mid, receiver = output, name = 'link_mid_to_output')
link_input_to_mid = pnl.MappingProjection(sender = input, receiver = mid, name = 'link_input_to_mid')
comp = pnl.Composition(name = 'comp')

comp.add_node(output)
comp.add_node(mid)
comp.add_node(input)

comp.add_projection(link_mid_to_output)
comp.add_projection(link_input_to_mid)

gv_node = comp.show_graph(show_node_structure=pnl.ALL, output_fmt="gv")
gv_node.pipe('json', quiet=True).decode()

# comp.run(inputs=[10, 1, 2, 3, 4, 5, 10, 7])
# print(comp.results)
```

**Comment by kmantel** [comment]
I noticed that there was no error if `comp.show_graph(show_node_structure=pnl.ALL)` was called before show_graph with 'gv'. It looks related to these lines

https://github.com/PrincetonUniversity/PsyNeuLink/blob/1ea4407c66e304cd564d0c03e02e5b77663be419/psyneulink/core/compositions/showgraph.py#L850-L853

If the _analyze_graph gets called, the error also goes away, but I'm not sure the reason it's skipped for 'gv' @jdcpni

**Comment by taylor-curley** [comment]
I had the same issue when building this in a Jupyter Notebook via Anaconda [^1] and found that `graphviz` only works when you install the complete C bindings/Python library, i.e.:

`conda install python-graphviz`

Specifying `graphviz` will not install all of the components necessary for visualizing `psyneulink` models. See [this StackOverflow post](https://stackoverflow.com/questions/73830695/failed-to-execute-posixpathdot-make-sure-the-graphviz-executables-are-on-y) for a related discussion. Hope that helps.

[^1]: It's worth noting that I specifically installed and created models in separate `conda` environment using `python=3.10.12`, which is the only Python distribution that I personally can run `psyneulink` models in.

**Comment by kmantel** [comment]
> I had the same issue when building this in a Jupyter Notebook via Anaconda [1](#user-content-fn-1-518bef931097f770e1faff61548aaaeb) and found that `graphviz` only works when you install the complete C bindings/Python library, i.e.:
> 
> `conda install python-graphviz`
> 
> Specifying `graphviz` will not install all of the components necessary for visualizing `psyneulink` models. See [this StackOverflow post](https://stackoverflow.com/questions/73830695/failed-to-execute-posixpathdot-make-sure-the-graphviz-executables-are-on-y) for a related discussion. Hope that helps.
> ## Footnotes
> 
>     1. It's worth noting that I specifically installed and created models in separate `conda` environment using `python=3.10.12`, which is the only Python distribution that I personally can run `psyneulink` models in. [↩](#user-content-fnref-1-518bef931097f770e1faff61548aaaeb)

Making a better error message for this issue is also on the todo list. 

I'm not familiar with it - are you saying `conda install python-graphviz` also handles installing the system packages, not just python?

**Comment by taylor-curley** [comment]
> I'm not familiar with it - are you saying conda install python-graphviz also handles installing the system packages, not just python?

Yes, pretty much. I'm not as well-versed in the differences, but the top answer in this thread gives a pretty good overview:

https://stackoverflow.com/questions/37353199/graphviz-vs-pygraphviz

**Comment by ddelpiano** [comment]
@kmantel  @taylor-curley I am running this in a conda env with python 3.10 and I can confirm that python-graphviz is already installed, it's one of the few depedencies we install prior installing the viewer

```
echo "### installing graphviz ###"
conda install -y python-graphviz

echo "### removing grpcio ###"
pip uninstall -y grpcio && pip uninstall -y grpcio-tools

echo "### installing grpcio ###"
conda install -y -c conda-forge grpcio

echo "### installing modeci_mdf ###"
pip install modeci_mdf
```

**Comment by kmantel** [comment]
@ddelpiano 

Yes I think that's a separate issue to what you're experiencing. 

I think I was a bit unclear before, would you be able to add `comp._analyze_graph()` to model.py above `gv_node = comp.show_graph(show_node_structure=pnl.ALL, output_fmt="gv")`? That avoids the error with that script for me and is tangentially what I was referencing in my first comment, which I see was more about the root of the problem.

**Comment by ddelpiano** [comment]
@kmantel the above solved the problem we had, if you are ok we can close this. Thanks!
